seed: 42
sampling_rate_hz: 1000000   # 1 MHz
classes: ["BF", "GF", "N", "TF"]
data:
  index_csv: "data/signals.csv"   # columns: filepath,label
  signal_column: "filepath"
  label_column: "label"
  file_type: "npy"                # "npy" or "csv"
preprocess:
  wavelet: "db4"
  level: null            # auto
  soft_hard_alpha: 0.8   # hybrid soft-hard mix
  burst:
    win_ms: 1.0          # short-time energy window
    alpha: 3.0           # energy ratio threshold
    pad_ms: 0.2          # context around burst
    max_segments: 10
features:
  tfd:
    cwt_wavelet: "morl"
    scales: 32
selection:
  top_k_filter: 64       # mutual information prefilter
  embedded_model: "xgb"  # "xgb" or "rf"
  final_dim: 64
train:
  test_size: 0.2
  val_size: 0.1
  stratify: true
  scaler: "minmax"
ensemble:
  tabnet:
    n_d: 64
    n_a: 64
    n_steps: 5
    gamma: 1.3
    clip_value: 2.0
    epochs: 100
    batch_size: 256
    lr: 0.002
  xgb:
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 6
    subsample: 0.8
    colsample_bytree: 0.8
  svm:
    C: 1.0
    kernel: "poly"
    degree: 3
    gamma: "scale"
  meta_rf:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 2
logging:
  out_dir: "outputs"
